name: linkops-staging
services:
  web:
    image: ghcr.io/mohamedaleya/linkops:staging
    container_name: web-staging
    restart: always
    ports:
      - 3071:3000
    env_file: .env.staging
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: postgres-staging
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: linkops_staging
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-staging
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data_staging:/data

volumes:
  postgres_data_staging:
  redis_data_staging:
